In [1]:
import numpy as np
from scipy import sparse

This chapter is explictly for showing array and matrix creation. After creation many manipulation stratigies used for ML are applied include transposing, variance/standard deviation, determinant, trace, rank, and Eigenvectors/values. Using industry standard libraries scipy and numpy.

In [2]:
#create vectors
vector_row = np.array([1,2,3,4,5,6,7,8,9])
vector_column = np.array([[1],
                         [2],
                         [3],
                         [4],
                         [5],
                         [6],
                         [7],
                         [8],
                         [9]])

In [3]:
#selecting elements
vector_row[2]
vector_column[6]

#select all
vector_column[:]

#everything including the third
vector_row[:3]

array([1, 2, 3])

In [4]:
#create matrix
matrix = np.mat([[1,2],
               [2,3],
               [3,4],
               [4,5],
               [5,6],
               [6,7],
               [7,8],
               [8,9],
                [9,9]])

In [5]:
#selecting elements everything after third and in second column
matrix[3:,1]

#select first four rows
matrix[:4,:]

#add ten to each element
matrix + 10

matrix([[11, 12],
        [12, 13],
        [13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 19]])

In [6]:
#create sparse matrix
zeros_matrix = np.array([[0, 1],
                        [0,0],
                        [5,0],
                        [0,5],
                        [5,0]])

#csr = compressed sparse row
sparse_matrix = sparse.csr_matrix(zeros_matrix)
#print coordinates of non-zero values in matrix and the value
print(sparse_matrix)

  (0, 1)	1
  (2, 0)	5
  (3, 1)	5
  (4, 0)	5


In [7]:
#size shape and ndim(dimensions)
shape_matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

shape_matrix.shape
shape_matrix.size
shape_matrix.ndim

2

In [8]:
#create function and vectorize
function_matrix = np.array([[2,4,4],
                          [12,23,3],
                          [7,1,14]])

#function to add 100
add_100 = lambda x: x + 100 

#np vectorize
vectorize_adding = np.vectorize(add_100)

#add 100
vectorize_adding(function_matrix)


#NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array.
#for more complex functions instead of the simple matrix + 10 in cells above

array([[102, 104, 104],
       [112, 123, 103],
       [107, 101, 114]])

In [9]:
# Create matrix
matrix = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])


#finding min and max
np.max(matrix)
np.min(matrix)

#min and max for dimension zero
np.max(matrix, axis=0)

#min and max for dimension one
np.max(matrix, axis=1)

#min and max for dimension two
np.max(matrix, axis=2)

array([[3, 6, 9]])

In [10]:
# mean variance and standard deviation
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

np.mean(matrix)
np.var(matrix)
np.std(matrix)

#find the mean of a each column
np.mean(matrix, axis=0)

#find mean of each row
np.mean(matrix, axis=1)

array([2., 5., 8.])

In [11]:
#reshaping arrays
matrix_reshape = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

#single row
matrix_reshape.reshape(1,12)

#two rows
matrix_reshape.reshape(2,6)

#six rows
matrix_reshape.reshape(6,2)

#reshape to one dimension
matrix_reshape.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
#Transposing
transpose_matrix = np.array([[2,4,6],
                            [8,10,12],
                            [14,16,18]])

np.transpose(transpose_matrix)


# Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. 
# One nuanced point that is typically overlooked outside of a linear algebra class is that, 
# technically, a vector cannot be transposed because it is just a collection of values:

#cant transpose
np.array([1,2,3,4,5,6]).T

#can transpose
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
#Flattening matrix
flatten_matrix = np.array([[1,1,2],
                          [3,5,8],
                          [13,21,34]])

flatten_matrix.flatten()

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34])

In [29]:
#randomize matrix
rank_matrix = np.matrix(np.random.randint(0,3, size=(3, 3)))
rank_matrix

matrix([[0, 0, 0],
        [2, 2, 0],
        [1, 1, 2]])

In [30]:
#rank the matrix
# The rank of a matrix is the dimensions of the vector space spanned by its columns or rows.
np.linalg.matrix_rank(rank_matrix)

2

In [41]:
#calculate determinant
#The determinant of a linear transformation measures how much areas/volumes change during the transformation.
deter_matrix = np.matrix(np.random.randint(0,5, size=(3, 3)))
np.linalg.det(deter_matrix)


23.999999999999993

In [54]:
#get the diagonal of a matrix
diagonal_martix = np.matrix(np.random.randint(1,10, size=(3, 3)))
diagonal_martix.diagonal()

matrix([[4, 3, 4]])

In [55]:
#diagonal with offset
diagonal_martix.diagonal(offset=1)

matrix([[9, 5]])

In [56]:
#matrix trace 
# sum of the diagonal values, possible with offset
diagonal_martix.trace()

matrix([[11]])

In [58]:
#Find the eigenvalues and eigenvectors of a square matrix 
eigen_matrix = np.matrix(np.random.randint(1,10,size=(3,3)))

eigen_matrix

matrix([[3, 7, 3],
        [2, 4, 2],
        [1, 5, 1]])

In [61]:
#calculate values and vectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
eigenvalues
eigenvectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [63]:
#dot plots
vector_a = np.array([1,2,3,4])
vector_b = np.array([11,22,33,44])
np.dot(vector_a, vector_b)

#or python 3.5+ 
vector_a @ vector_b

330

In [68]:
#add, substract, multi, divide matrix
vector_a + vector_b

vector_a - vector_b

vector_a * vector_b

vector_a / vector_b

array([0.09090909, 0.09090909, 0.09090909, 0.09090909])

In [77]:
# invert matrix 
invert_matrix = np.matrix(np.random.randint(1,10,size=(3,3)))
invert_matrix

matrix([[2, 1, 4],
        [7, 9, 1],
        [6, 6, 1]])

In [78]:
np.linalg.inv(invert_matrix)

matrix([[-0.06976744, -0.53488372,  0.81395349],
        [ 0.02325581,  0.51162791, -0.60465116],
        [ 0.27906977,  0.13953488, -0.25581395]])